### ISSUE TITLE
More efficient caching and handling collisions

### ISSUE THREAD

**Issue by B-Teague** [lukejacksonn/csz#1]
Use the string as the key for the cache and the hash as the data value.  Calculate the hash only when creating a new key.  Store the hash values in a second lookup map and check when creating a new hash value to detect collisions.

OR

Do what picostyle does and increment a classname counter for each new unique string value.

**Comment by lukejacksonn** [comment]
This does sound like a way better approach; for context this was discussed in a thread on hyperapp slack. The only doubt we had was on the limitation and perf implications of keys in JavaScript object.. but after some research it seems that neither of these things are limiting (at least for all practical applications) and so I say we give it a go!

If you have time then please go ahead and make a PR, if not I will get around to it as soon as I can 🙇

**Comment by lukejacksonn** [comment]
Turns out key lookup speed is considered constant and so I made the decision to just use the supplied ruleset or filepath as the key to the cache. This way we know if we have seen the ruleset before without any hashing.

I'm not quite sure what the implications of this decision might be yet but it is an internal API decision and the implementation can easily be iterated on, so I'd love to hear any thoughts on how it could be improved 🙌
