### ISSUE TITLE
using csz's file import in snowpack setup breaks the dev server's hmr.

### ISSUE THREAD

**Issue by Manish3323** [lukejacksonn/csz#15]
i have put this question on pika discuss forum as well. putting it here as i think its intertwined with snowpack's way of importing css files.
i have one component.css file which i am importing like this in component.tsx file.
```
const componentStyle = css`/component.css`

// usage
<div className={componentStyle}>
// ..some html here//
</div>
```
since this css file is not imported using top level import but is inside csz's template literal.
any changes made to this landing.css file doesn't reflect .. i have to  restart the snowpack's dev server to see the new changes.
i explored my sources tab in chrome's console tool. since snowpack didn't encountered any import of css file it was not served and hence this doesn't work.
but some where down the line csz's framework takes care of that adding the style to  the dom.
i am not sure this is the ideal scenario for snowpack to pick up file (which is not imported using import but is inside css string literal )and serve it.
is there a setup or repo which i can use it as a reference where csz is used in a snowpack setup and also css files are imported in .jsx/.tsx files.

**Comment by lukejacksonn** [comment]
Hey 👋 thanks for investigating this!

Unfortunately this is a side effect of HMR relying on getting its file graph data from parsing actual imports (which is generally a good thing) and csz using a completely custom import syntax (uses template literal and fetch instead, as importing css is not yet supported by the browser).

I'm not sure what to suggest here, until dynamic import of CSS becomes standard then we have to think of a call for an external file like this as a fetch request (which wouldn't normally cause a refresh).

Does refreshing the page not cause the styles to update. Unless HMR is caching fetch requests then you shouldn't have to restart the server entirely. Not an idea solution I know, but slightly better!

**Comment by Manish3323** [comment]
Thanks for replying quickly.

unfortunately refreshing browser doesn't work :(
however i will check this, if there's a way to configure snowpack to cache fetch request. 

Nice little library though. very impressive work!! 💯

**Comment by lukejacksonn** [comment]
No worries! It is an interesting problem.. I know that there is a shim for css imports in https://github.com/guybedford/es-module-shims but I am not sure how that will play with snowpacks build either 🤷‍♂️ 

Let me know if you get to the bottom of it.. otherwise perhaps we can consult one of the snowpack folk or my colleague who implemented the hot module reloading for snowpack.

**Comment by Manish3323** [comment]
Sure thing.
i have put this same question on pika discuss also .i'm sure the moderators will have say in this. meanwhile i'll learn about es-module-shims.

**Comment by Manish3323** [comment]
okay.. i feel bit embarrassed now. found that the problem is something unrelated to csz and snowpack. the initials of folder were css are located were in capital n i had put lowercase folder. 🙈 🤦‍♂️ 

this raises another question in my mind. if csz could handle relative imports, problems like i had would be less likely to happen.if there's a way to put relative path inside csz's string literal .. as in large projects where components can be situated deep inside folder structures, developer will not have to put full absolute path like this
```
const style = css`/_dist_/components/Landing/Landing.css` 
```
but instead have something like this 
```
const style = css`/./Landing.css`
```
first slash is necessary i guess to distinguish the inline css and css file.
ill give a try to incorporate relative imports in csz and send a PR. unless they were some reasons which restricted you to have relative imports in first place.

**Comment by lukejacksonn** [comment]
Ahh cool. So maybe my assumptions about HMR getting all its graph data from parsing code wasn't correct then 😅 

Regards relative links, it wasn't really a choice either! This was due to lack of support for [`import.meta`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta) which allows you to infer the location of the location of the calling script. From there you can build up relative paths.

Until then I think we are stuck with absolute links.. but I would be interesting in seeing an implementation ready for when import meta is standardised!
